screen=SHARPENING CAS_AMOUNT DH_FOG_START SSAO_SAMPLES SSAO_RADIUS SSAO_INTENSITY SSAO_BIAS DH_OVERDRAW DH_NOISE
sliders=CAS_AMOUNT DH_FOG_START SSAO_SAMPLES DH_OVERDRAW SSAO_RADIUS SSAO_INTENSITY SSAO_BIAS
uniform.float.framemod8 = frameCounter % 8
